export const GET_ALL_COMMENT_SAGA = "GET_ALL_COMMENT_SAGA";

export const GET_ALL_COMMENT = "GET_ALL_COMMENT";

export const INSERT_COMMENT = "INSERT_COMMENT";

export const INSERT_COMMENT_SAGA = "INSERT_COMMENT_SAGA";
