export const USER_SIGNIN_API = "USER_SIGNIN_API";

export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY";

export const GET_ALL_PROJECT = "GET_ALL_PROJECT";

export const CREATE_PROJECT_SAGA = "CREATE_PROJECT_SAGA";

export const USLOGIN = "USLOGIN";
