export const USER_SIGNIN_API = "USER_SIGNIN_API";

export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY";

export const GET_ALL_PROJECT = "GET_ALL_PROJECT";

export const CREATE_PROJECT_SAGA = "CREATE_PROJECT_SAGA";

export const USLOGIN = "USLOGIN";

export const GET_LIST_PROJECT_SAGA = "GET_LIST_PROJECT_SAGA";

export const GET_LIST_PROJECT = "GET_LIST_PROJECT";

export const OPEN_DRAWER = "OPEN_DRAWER";

export const CLOSE_DRAWER = "CLOSE_DRAWER";

export const OPEN_FORM_EDIT_PROJECT = "OPEN_FORM_EDIT_PROJECT";

export const OPEN_FORM = "OPEN_FORM";

export const SET_EDIT_SUBMIT_PROJECT = "SET_EDIT_SUBMIT_PROJECT";

export const EDIT_PROJECT = "EDIT_PROJECT";

export const UPDATE_PROJECT_SAGA = "UPDATE_PROJECT_SAGA";

export const DELETE_PROJECT_SAGA = "DELETE_PROJECT_SAGA";

export const GET_USER_API = "GET_USER_API";

export const GET_USER_SEARCH = "GET_USER_SEARCH";

export const ADD_USER_PROJECT_API = "ADD_USER_PROJECT_API";

export const REMOVE_USER_PROJECT_API = "REMOVE_USER_PROJECT_API";

export const GET_PROJECT_DETAIL_API = "GET_PROJECT_DETAIL";

export const PUT_PROJECT_DETAIL = "PUT_PROJECT_DETAIL";

export const OPEN_FORM_CREATE_TASK = "OPEN_FORM_CREATE_TASK";
