export const USER_SIGNIN_API = "USER_SIGNIN_API";

export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY";

export const GET_ALL_PROJECT = "GET_ALL_PROJECT";

export const CREATE_PROJECT_SAGA = "CREATE_PROJECT_SAGA";

export const USLOGIN = "USLOGIN";

export const GET_LIST_PROJECT_SAGA = "GET_LIST_PROJECT_SAGA";

export const GET_LIST_PROJECT = "GET_LIST_PROJECT";

export const OPEN_DRAWER = "OPEN_DRAWER";

export const CLOSE_DRAWER = "CLOSE_DRAWER";

export const OPEN_FORM_EDIT_PROJECT = "OPEN_FORM_EDIT_PROJECT";

export const OPEN_FORM = "OPEN_FORM";
