export const CREATE_TASK_SAGA = "CREATE_TASK_SAGA";

export const CREATE_TASK = "CREATE_TASK";

export const GET_TASK_DETAIL_SAGA = "GET_TASK_DETAIL_SAGA";

export const GET_TASK_DETAIL = "GET_TASK_DETAIL";
