export const GET_LIST_USER_SAGA = "GET_LIST_USER_SAGA";

export const GET_LIST_USER = "GET_LIST_USER";

export const EDIT_USER = "EDIT_USER";

export const UPDATE_USER_SAGA = "UPDATE_USER_SAGA";

export const DELETE_USER_SAGA = "DELETE_USER_SAGA";

export const USER_LIST_FILTER = "USER_LIST_FILTER";
